#!/usr/bin/env node
/**
 * "고정확도 엔진" 설치 프로그램(.pkg) 빌더 (macOS).
 *
 * 사용자가 하는 일: 사이드패널의 [고정확도 엔진 설치] -> 내려받은 pkg 두 번 클릭 -> 끝.
 * 터미널도, 확장 ID 복사도 없다. 확장 ID 는 이 스크립트가 Chrome 프로필에서 직접 찾아 넣는다.
 *
 * pkg 안에 들어가는 것:
 *   /Library/Application Support/StudyWhisper/study-whisper-host   (Chrome 이 실행할 런처)
 *   /Library/Google/Chrome 계열의 NativeMessagingHosts/com.study.whisper.json  (등록 매니페스트)
 *
 * 한계(정직하게): 이 pkg 는 whisper.cpp 바이너리/모델/node 를 담지 않는다. 이 컴퓨터에 이미 있는
 * 저장소를 가리킬 뿐이다. 스토어 배포판은 이 셋을 함께 담고 Apple 서명·공증을 받아야 한다.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { detectExtensionIds, idsFromInstalledManifests, isExtensionId } from './ext-ids.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const hostRoot = path.resolve(here, '..');
const repoRoot = path.resolve(hostRoot, '../..');
const distPath = path.join(repoRoot, 'apps/extension/dist');

const HOST_NAME = 'com.study.whisper';
const PKG_ID = 'com.study.whisper.engine';
const SUPPORT_DIR = '/Library/Application Support/StudyWhisper';
const LAUNCHER_PATH = `${SUPPORT_DIR}/study-whisper-host`;
const MANIFEST_DIRS = [
  '/Library/Google/Chrome/NativeMessagingHosts',
  '/Library/Google/Chrome Beta/NativeMessagingHosts',
  '/Library/Google/Chrome Canary/NativeMessagingHosts',
  '/Library/Application Support/Chromium/NativeMessagingHosts'
];

function fail(message) {
  console.error(message);
  process.exit(1);
}

function nodeBin() {
  // Chrome 이 런처를 exec 할 때는 PATH 에 nvm/homebrew 가 없을 수 있다. 지금 이 node 의 절대 경로를 박는다.
  return process.execPath;
}

function collectIds() {
  const fromArgs = process.argv.slice(2);
  const fromEnv = String(process.env.EXTRA_EXTENSION_IDS ?? '').split(',');
  const ids = new Set(
    [...fromArgs, ...fromEnv, ...detectExtensionIds(distPath), ...idsFromInstalledManifests(HOST_NAME)]
      .map((id) => id.trim())
      .filter(Boolean)
  );
  const bad = [...ids].filter((id) => !isExtensionId(id));
  if (bad.length) fail(`확장 ID 형식이 아닙니다: ${bad.join(', ')}`);
  return [...ids];
}

function main() {
  if (os.platform() !== 'darwin') fail('이 빌더는 macOS 전용입니다(pkgbuild).');
  if (!fs.existsSync(path.join(hostRoot, 'src/host.mjs'))) fail('apps/native-host/src/host.mjs 를 찾지 못했습니다.');

  const ids = collectIds();
  if (ids.length === 0) {
    fail(
      [
        '확장 ID 를 찾지 못했습니다.',
        '1) chrome://extensions 에서 "개발자 모드" 를 켠다',
        `2) "압축해제된 확장 프로그램을 로드" 로 ${distPath} 를 연다`,
        '3) 이 명령을 다시 실행한다 (ID 는 자동으로 찾습니다)'
      ].join('\n')
    );
  }

  const stage = fs.mkdtempSync(path.join(os.tmpdir(), 'study-engine-pkg-'));
  const payload = path.join(stage, 'payload');
  const supportDir = path.join(payload, SUPPORT_DIR.slice(1));
  fs.mkdirSync(supportDir, { recursive: true });

  const launcher = path.join(supportDir, 'study-whisper-host');
  fs.writeFileSync(
    launcher,
    `#!/bin/sh\n# Chrome Native Messaging launcher (generated by build-pkg.mjs)\nexec "${nodeBin()}" "${path.join(hostRoot, 'src/host.mjs')}" "$@"\n`
  );
  fs.chmodSync(launcher, 0o755);

  const manifest = `${JSON.stringify(
    {
      name: HOST_NAME,
      description: 'study sidepanel local whisper gateway launcher',
      path: LAUNCHER_PATH,
      type: 'stdio',
      allowed_origins: ids.map((id) => `chrome-extension://${id}/`)
    },
    null,
    2
  )}\n`;
  for (const dir of MANIFEST_DIRS) {
    const target = path.join(payload, dir.slice(1));
    fs.mkdirSync(target, { recursive: true });
    fs.writeFileSync(path.join(target, `${HOST_NAME}.json`), manifest);
  }

  // 확장속성이 남으면 pkg 안에 ._ 짝파일이 같이 들어간다. 설치본을 깨끗하게 유지한다.
  try {
    execFileSync('/usr/bin/xattr', ['-c', '-r', payload], { stdio: 'ignore' });
  } catch {
    /* xattr 이 없어도 설치 자체에는 문제가 없다 */
  }

  const outDir = path.join(hostRoot, 'dist');
  fs.mkdirSync(outDir, { recursive: true });
  const out = path.join(outDir, 'SideNoteEngine.pkg');
  const version = new Date().toISOString().slice(0, 10).replace(/-/g, '.');
  execFileSync(
    '/usr/bin/pkgbuild',
    ['--root', payload, '--identifier', PKG_ID, '--version', version, '--ownership', 'recommended', '--install-location', '/', out],
    { stdio: 'inherit' }
  );

  // 확장 패키지 안에는 넣지 않는다. 지금 배포판(SideNote)은 Chrome 기기 내 음성인식만 쓰고
  // 외부 엔진과 말을 섞지 않으므로(nativeMessaging 권한 없음), 이 pkg 는 이 워크스페이스 안에만 둔다.
  console.log(`\n확장 ID: ${ids.join(', ')}`);
  console.log(`설치 프로그램: ${out}`);
  console.log('\n담긴 파일:');
  console.log(execFileSync('/usr/sbin/pkgutil', ['--payload-files', out], { encoding: 'utf8' }).trim());
}

main()
