#!/usr/bin/env bash
# Idempotent whisper.cpp installer for macOS / Linux.
# Usage: ./scripts/setup-whisper.sh [model]   (default: small)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENDOR="$ROOT/vendor/whisper.cpp"
BUILD="$VENDOR/build"
MODELS="$ROOT/models"
MODEL="${1:-small}"
MODEL_FILE="$MODELS/ggml-${MODEL}.bin"
REPO="https://github.com/ggml-org/whisper.cpp.git"

log(){ printf '\033[36m[setup-whisper]\033[0m %s\n' "$*"; }
die(){ printf '\033[31m[setup-whisper] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

command -v git   >/dev/null 2>&1 || die "git 이 필요합니다. (macOS: xcode-select --install)"
command -v cmake >/dev/null 2>&1 || die "cmake 가 필요합니다. (macOS: brew install cmake)"

mkdir -p "$ROOT/vendor" "$MODELS"

# 1. source ---------------------------------------------------------------
if [ ! -d "$VENDOR/.git" ]; then
  log "whisper.cpp clone 중..."
  rm -rf "$VENDOR"
  git clone --depth 1 "$REPO" "$VENDOR"
else
  log "whisper.cpp 이미 존재. 재사용."
fi

# 2. build ----------------------------------------------------------------
SERVER_BIN=""
for c in "$BUILD/bin/whisper-server" "$BUILD/bin/Release/whisper-server"; do
  [ -x "$c" ] && SERVER_BIN="$c" && break
done

if [ -z "$SERVER_BIN" ] || [ "${FORCE_REBUILD:-0}" = "1" ]; then
  log "cmake configure..."
  cmake -S "$VENDOR" -B "$BUILD" -DCMAKE_BUILD_TYPE=Release -DWHISPER_BUILD_SERVER=ON -DWHISPER_BUILD_TESTS=OFF
  log "cmake build (수 분 소요)..."
  cmake --build "$BUILD" --config Release -j "$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)" --target whisper-server whisper-cli
  for c in "$BUILD/bin/whisper-server" "$BUILD/bin/Release/whisper-server"; do
    [ -x "$c" ] && SERVER_BIN="$c" && break
  done
else
  log "whisper-server 바이너리 이미 존재. 빌드 생략. (재빌드: FORCE_REBUILD=1 $0)"
fi

[ -n "$SERVER_BIN" ] || die "whisper-server 빌드 실패 — $BUILD/bin 을 확인하세요."

# 3. model ----------------------------------------------------------------
if [ -f "$MODEL_FILE" ] && [ "$(wc -c <"$MODEL_FILE" | tr -d ' ')" -gt 1000000 ]; then
  log "모델 이미 존재: $MODEL_FILE"
else
  log "ggml-${MODEL}.bin 다운로드 중... (large 계열은 1GB 이상이라 오래 걸립니다)"
  # 받다가 중단되면 잘린 파일이 남고, 위의 크기 검사를 통과해 "이미 존재" 로 오인된다.
  # 임시 폴더에 받아서 성공했을 때만 옮긴다.
  STAGE="$MODELS/.downloading"
  rm -rf "$STAGE"
  mkdir -p "$STAGE"
  if bash "$VENDOR/models/download-ggml-model.sh" "$MODEL" "$STAGE" && [ -f "$STAGE/ggml-${MODEL}.bin" ]; then
    mv "$STAGE/ggml-${MODEL}.bin" "$MODEL_FILE"
    rm -rf "$STAGE"
  else
    rm -rf "$STAGE"
    die "모델 다운로드 실패: ggml-${MODEL}.bin — 네트워크를 확인하고 다시 실행하세요."
  fi
fi

# 4. env ------------------------------------------------------------------
cat > "$ROOT/.whisper-env" <<ENVEOF
# generated by scripts/setup-whisper.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
WHISPER_SERVER_BIN=$SERVER_BIN
WHISPER_MODEL=$MODEL_FILE
ENVEOF

log "완료."
log "  server : $SERVER_BIN"
log "  model  : $MODEL_FILE ($(du -h "$MODEL_FILE" | cut -f1))"
log "  env    : $ROOT/.whisper-env"
